2021-05-27 19:11:41,124 INFO    MainThread:14124 [wandb_setup.py:_flush():69] setting env: {}
2021-05-27 19:11:41,124 INFO    MainThread:14124 [wandb_setup.py:_flush():69] setting login settings: {}
2021-05-27 19:11:41,124 INFO    MainThread:14124 [wandb_init.py:_log_setup():336] Logging user logs to C:\Users\lucas\Documents\GitHub\ViT\wandb\run-20210527_191141-2wzz9zjd\logs\debug.log
2021-05-27 19:11:41,124 INFO    MainThread:14124 [wandb_init.py:_log_setup():337] Logging internal logs to C:\Users\lucas\Documents\GitHub\ViT\wandb\run-20210527_191141-2wzz9zjd\logs\debug-internal.log
2021-05-27 19:11:41,124 INFO    MainThread:14124 [wandb_init.py:init():369] calling init triggers
2021-05-27 19:11:41,124 INFO    MainThread:14124 [wandb_init.py:init():374] wandb.init called with sweep_config: {}
config: {}
2021-05-27 19:11:41,124 INFO    MainThread:14124 [wandb_init.py:init():418] starting backend
2021-05-27 19:11:41,124 INFO    MainThread:14124 [backend.py:_multiprocessing_setup():69] multiprocessing start_methods=spawn, using: spawn
2021-05-27 19:11:41,124 INFO    MainThread:14124 [backend.py:ensure_launched():123] starting backend process...
2021-05-27 19:11:41,202 INFO    MainThread:14124 [backend.py:ensure_launched():127] started backend process with pid: 19108
2021-05-27 19:11:41,202 INFO    MainThread:14124 [wandb_init.py:init():423] backend started and connected
2021-05-27 19:11:41,202 INFO    MainThread:14124 [wandb_init.py:init():463] updated telemetry
2021-05-27 19:11:41,217 INFO    MainThread:14124 [wandb_init.py:init():482] communicating current version
2021-05-27 19:11:42,940 INFO    MainThread:14124 [wandb_init.py:init():487] got version response upgrade_message: "wandb version 0.10.31 is available!  To upgrade, please run:\n $ pip install wandb --upgrade"

2021-05-27 19:11:42,948 INFO    MainThread:14124 [wandb_init.py:init():495] communicating run to backend with 30 second timeout
2021-05-27 19:11:43,602 INFO    MainThread:14124 [wandb_init.py:init():520] starting run threads in backend
2021-05-27 19:11:45,766 WARNING MainThread:14124 [wandb_init.py:init():765] interrupted
Traceback (most recent call last):
  File "C:\Users\lucas\anaconda3\envs\tcc\lib\site-packages\wandb\sdk\wandb_init.py", line 745, in init
    run = wi.init()
  File "C:\Users\lucas\anaconda3\envs\tcc\lib\site-packages\wandb\sdk\wandb_init.py", line 523, in init
    _ = backend.interface.communicate_run_start(run_obj)
  File "C:\Users\lucas\anaconda3\envs\tcc\lib\site-packages\wandb\sdk\interface\interface.py", line 777, in communicate_run_start
    result = self._communicate(rec)
  File "C:\Users\lucas\anaconda3\envs\tcc\lib\site-packages\wandb\sdk\interface\interface.py", line 527, in _communicate
    return self._communicate_async(rec, local=local).get(timeout=timeout)
  File "C:\Users\lucas\anaconda3\envs\tcc\lib\site-packages\wandb\sdk\interface\interface.py", line 82, in get
    is_set = self._object_ready.wait(timeout)
  File "C:\Users\lucas\anaconda3\envs\tcc\lib\threading.py", line 558, in wait
    signaled = self._cond.wait(timeout)
  File "C:\Users\lucas\anaconda3\envs\tcc\lib\threading.py", line 306, in wait
    gotit = waiter.acquire(True, timeout)
KeyboardInterrupt
